#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-Abstract
version:      1.006
version_from: Abstract.pm
installdirs:  site
requires:
    DBI:                           0
    Scalar::Util:                  0
    Test::Simple:                  0.44

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
